"""
Waste to Landfill Comparison: Electric vs Gas Vehicles

This script analyzes and compares the waste generated by EVs and ICE vehicles
over their lifetime, including:
- Maintenance waste (oil, filters, fluids)
- Battery disposal/recycling
- Tire wear
- End-of-life disposal
"""

import pandas as pd
import numpy as np
from pathlib import Path

# Project paths
PROJECT_ROOT = Path(__file__).parent.parent.parent
DATA_DIR = PROJECT_ROOT / "data"
OUTPUT_DIR = PROJECT_ROOT / "outputs"


# ============================================================================
# BASELINE DATA - Average vehicle lifetime waste estimates
# Sources: EPA, academic lifecycle studies
# Units: pounds (lbs) over 15-year/200,000 mile vehicle lifetime
# ============================================================================

# Gas/ICE Vehicle Waste (over 15 years / 200k miles)
GAS_VEHICLE_WASTE = {
    "oil_changes": {
        "frequency_miles": 5000,  # every 5k miles
        "oil_quarts": 5,
        "oil_weight_lbs": 10,  # ~5 quarts of oil
        "filter_weight_lbs": 1,
    },
    "transmission_fluid": {
        "frequency_miles": 60000,
        "fluid_lbs": 10,
    },
    "coolant": {
        "frequency_miles": 30000,
        "fluid_lbs": 8,
    },
    "brake_pads": {
        "frequency_miles": 50000,  # depends on driving
        "weight_lbs_per_set": 8,
    },
    "brake_rotors": {
        "frequency_miles": 70000,
        "weight_lbs_per_set": 40,
    },
    "spark_plugs": {
        "frequency_miles": 100000,
        "weight_lbs": 0.5,
    },
    "air_filters": {
        "frequency_miles": 15000,
        "weight_lbs": 1,
    },
    "fuel_filters": {
        "frequency_miles": 30000,
        "weight_lbs": 1,
    },
    "belts_hoses": {
        "frequency_miles": 60000,
        "weight_lbs": 5,
    },
    "exhaust_system": {
        "frequency_miles": 100000,  # muffler, catalytic converter
        "weight_lbs": 50,
    },
    "tires": {
        "frequency_miles": 50000,
        "weight_lbs_per_set": 100,  # 4 tires ~25 lbs each
    },
}

# Electric Vehicle Waste (over 15 years / 200k miles)
EV_WASTE = {
    "coolant": {
        "frequency_miles": 50000,  # less frequent than ICE
        "fluid_lbs": 8,
    },
    "brake_pads": {
        "frequency_miles": 100000,  # regen braking extends life significantly
        "weight_lbs_per_set": 8,
    },
    "brake_rotors": {
        "frequency_miles": 150000,  # much longer life due to regen
        "weight_lbs_per_set": 40,
    },
    "tires": {
        "frequency_miles": 40000,  # EVs are heavier, wear tires faster
        "weight_lbs_per_set": 100,
    },
    "cabin_air_filter": {
        "frequency_miles": 15000,
        "weight_lbs": 0.5,
    },
    "battery_pack": {
        # End of life consideration
        "weight_lbs": 1000,  # average EV battery pack
        "recyclable_percent": 95,  # lithium-ion recycling rate improving
        "landfill_percent": 5,  # what ends up in landfill
    },
}


def calculate_lifetime_waste(vehicle_type: str, lifetime_miles: int = 200000) -> dict:
    """
    Calculate total waste generated over a vehicle's lifetime.
    
    Args:
        vehicle_type: 'gas' or 'ev'
        lifetime_miles: Total miles driven over vehicle lifetime
    
    Returns:
        Dictionary with waste breakdown and totals
    """
    waste_data = GAS_VEHICLE_WASTE if vehicle_type == "gas" else EV_WASTE
    waste_breakdown = {}
    total_waste = 0
    recyclable_waste = 0
    landfill_waste = 0
    
    for item, data in waste_data.items():
        if item == "battery_pack":
            # Special handling for EV battery
            landfill_lbs = data["weight_lbs"] * (data["landfill_percent"] / 100)
            recycled_lbs = data["weight_lbs"] * (data["recyclable_percent"] / 100)
            waste_breakdown[item] = {
                "total_lbs": data["weight_lbs"],
                "landfill_lbs": landfill_lbs,
                "recycled_lbs": recycled_lbs,
            }
            total_waste += data["weight_lbs"]
            recyclable_waste += recycled_lbs
            landfill_waste += landfill_lbs
        else:
            # Calculate based on frequency
            frequency = data.get("frequency_miles", lifetime_miles)
            replacements = lifetime_miles / frequency
            
            # Get weight per replacement
            if "weight_lbs" in data:
                weight = data["weight_lbs"]
            elif "weight_lbs_per_set" in data:
                weight = data["weight_lbs_per_set"]
            elif "oil_weight_lbs" in data:
                weight = data["oil_weight_lbs"] + data["filter_weight_lbs"]
            elif "fluid_lbs" in data:
                weight = data["fluid_lbs"]
            else:
                weight = 0
            
            total_lbs = replacements * weight
            waste_breakdown[item] = {
                "replacements": replacements,
                "weight_per_replacement": weight,
                "total_lbs": total_lbs,
            }
            total_waste += total_lbs
            
            # Estimate recyclability (metals recycled, fluids/rubber to landfill)
            if item in ["brake_rotors", "exhaust_system"]:
                recyclable_waste += total_lbs * 0.9  # metals highly recyclable
                landfill_waste += total_lbs * 0.1
            elif item in ["tires"]:
                recyclable_waste += total_lbs * 0.35  # tire recycling rate ~35%
                landfill_waste += total_lbs * 0.65
            elif item in ["oil_changes", "transmission_fluid", "coolant"]:
                recyclable_waste += total_lbs * 0.6  # oil recycling available
                landfill_waste += total_lbs * 0.4
            else:
                landfill_waste += total_lbs  # most other items go to landfill
    
    return {
        "vehicle_type": vehicle_type,
        "lifetime_miles": lifetime_miles,
        "waste_breakdown": waste_breakdown,
        "total_waste_lbs": total_waste,
        "recyclable_lbs": recyclable_waste,
        "landfill_lbs": landfill_waste,
    }


def compare_vehicles(lifetime_miles: int = 200000) -> pd.DataFrame:
    """
    Compare waste between gas and electric vehicles.
    """
    gas_waste = calculate_lifetime_waste("gas", lifetime_miles)
    ev_waste = calculate_lifetime_waste("ev", lifetime_miles)
    
    comparison = pd.DataFrame({
        "Metric": [
            "Total Waste (lbs)",
            "Recyclable Waste (lbs)",
            "Landfill Waste (lbs)",
            "Landfill %",
        ],
        "Gas Vehicle": [
            gas_waste["total_waste_lbs"],
            gas_waste["recyclable_lbs"],
            gas_waste["landfill_lbs"],
            (gas_waste["landfill_lbs"] / gas_waste["total_waste_lbs"]) * 100,
        ],
        "Electric Vehicle": [
            ev_waste["total_waste_lbs"],
            ev_waste["recyclable_lbs"],
            ev_waste["landfill_lbs"],
            (ev_waste["landfill_lbs"] / ev_waste["total_waste_lbs"]) * 100,
        ],
    })
    
    comparison["Difference"] = comparison["Gas Vehicle"] - comparison["Electric Vehicle"]
    
    return comparison, gas_waste, ev_waste


def main():
    """Run the waste comparison analysis."""
    print("=" * 60)
    print("ELECTRIC vs GAS VEHICLE WASTE COMPARISON")
    print("Lifetime: 15 years / 200,000 miles")
    print("=" * 60)
    print()
    
    comparison_df, gas_data, ev_data = compare_vehicles()
    
    print("SUMMARY COMPARISON")
    print("-" * 60)
    print(comparison_df.to_string(index=False))
    print()
    
    print("\nGAS VEHICLE WASTE BREAKDOWN")
    print("-" * 60)
    for item, data in gas_data["waste_breakdown"].items():
        print(f"  {item}: {data['total_lbs']:.1f} lbs")
    
    print("\nELECTRIC VEHICLE WASTE BREAKDOWN")
    print("-" * 60)
    for item, data in ev_data["waste_breakdown"].items():
        print(f"  {item}: {data['total_lbs']:.1f} lbs")
    
    print("\n" + "=" * 60)
    print("KEY FINDINGS")
    print("=" * 60)
    
    gas_landfill = gas_data["landfill_lbs"]
    ev_landfill = ev_data["landfill_lbs"]
    
    if gas_landfill > ev_landfill:
        print(f"✓ Gas vehicles send {gas_landfill - ev_landfill:.1f} MORE lbs to landfill")
    else:
        print(f"✓ EVs send {ev_landfill - gas_landfill:.1f} MORE lbs to landfill")
    
    print(f"✓ Gas vehicle landfill waste: {gas_landfill:.1f} lbs")
    print(f"✓ EV landfill waste: {ev_landfill:.1f} lbs")
    print()
    
    # Save results
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    comparison_df.to_csv(OUTPUT_DIR / "reports" / "waste_comparison.csv", index=False)
    print(f"Results saved to {OUTPUT_DIR / 'reports' / 'waste_comparison.csv'}")


if __name__ == "__main__":
    main()
